name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  linux:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wandb'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Install gpgme dependencies and 32-bit libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpgme-dev gcc-multilib
      - name: Set environment variables for CGO
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I/usr/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L/usr/lib" >> $GITHUB_ENV
      - name: Install Go dependencies
        run: go mod tidy
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: "~> v2" 
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CGO_ENABLED: 1
          CGO_CFLAGS: -I/usr/include
          CGO_LDFLAGS: -L/usr/lib
