name: "Run Tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get ./...
      - name: Verify modules
        run: go mod verify

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: go.sum
      - name: Install gpgme dependencies
        run: sudo apt-get update && sudo apt-get install -y libgpgme-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=5m

  fmt:
    name: Format
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: go.sum
      - name: Format
        run: make fmt

  dependency-check:
    name: Dependency Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Check for changes in go.mod or go.sum
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
